apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: PWA-CHAT
  description: PWA-CHAT (TypeScript)
  annotations:
    github.com/project-slug: tokyandria001/PWA-CHAT
  tags:
    - typescript
spec:
  type: website
  lifecycle: experimental
  owner: guests
