import type { Metadata } from "next";
import styles from "./page.module.css";
import Link from 'next/link';
import './globals.css';
import NotificationManager from "./components/NotificationManager";

export const metadata: Metadata = {
  title: "Create Next App !!",
  manifest: "/manifest.json",

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={styles.body}>
        <header className={styles.header}>
          <nav className={styles.nav}>
            <Link href="/" className={styles.navLink}>🏠 Accueil</Link>
            <Link href="/profile" className={styles.navLink}>Réception</Link>
          </nav>
        </header>
        <NotificationManager/>
        <main className={styles.main}>
          {children}
        </main>
      </body>
    </html>
  );
}
